@startuml Manage CoWorkingSpace (POST)

header Sameple VacQ Sequence Diagram
footer Page %page% of %lastpage%
title "Manage CoWorkingSpace (POST)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:coworkingspaces" as routerCWS
participant "<<controllers>>\n:coworkingspaces" as controllersCWS
participant "<<model>>\n:CoWorkingSpace" as modelCWS
database "<<MongoDB>>\n:coworkingspaces" as CWSDatabase

client->server ++:req.post('/api/v1/coworkingspaces')

server->routerCWS ++:app.use('/api/v1/coworkingspaces',coworkingspaces)

routerCWS -> controllersCWS ++:createCoWorkingSpace()

controllersCWS->modelCWS ++:create(req.body)

modelCWS ->CWSDatabase ++: CoWorkingSpaceSchema

CWSDatabase --> modelCWS --: coworkingspace

controllersCWS <-- modelCWS --:coworkingspace

controllersCWS->client --:response

@enduml


@startuml Manage CoWorkingSpace (GET ALL)

header Sameple VacQ Sequence Diagram
footer Page %page% of %lastpage%
title "Manage CoWorkingSpace (GET ALL)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:coworkingspaces" as routerCWS
participant "<<controllers>>\n:coworkingspaces" as controllersCWS
participant "<<model>>\n:CoWorkingSpace" as modelCWS
database "<<MongoDB>>\n:coworkingspaces" as CWSDatabase

client->server ++:req.get('/api/v1/coworkingspaces')

server->routerCWS ++:app.use('/api/v1/coworkingspaces',coworkingspaces)

routerCWS -> controllersCWS ++:getCoWorkingSpaces()

controllersCWS->modelCWS ++:find()

modelCWS ->CWSDatabase ++: CoWorkingSpaceSchema

CWSDatabase --> modelCWS --: coworkingspaces

controllersCWS <-- modelCWS --:coworkingspaces

controllersCWS->client --:response

@enduml

@startuml Manage CoWorkingSpace (GET ONE)

header Sameple VacQ Sequence Diagram
footer Page %page% of %lastpage%
title "Manage CoWorkingSpace (GET ONE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:coworkingspaces" as routerCWS
participant "<<controllers>>\n:coworkingspaces" as controllersCWS
participant "<<model>>\n:CoWorkingSpace" as modelCWS
database "<<MongoDB>>\n:coworkingspaces" as CWSDatabase

client->server ++:req.get('/api/v1/coworkingspaces/:id')

server->routerCWS ++:app.use('/api/v1/coworkingspaces',coworkingspaces)

routerCWS -> controllersCWS ++:getCoWorkingSpace()

controllersCWS->modelCWS ++:findById(id)

modelCWS ->CWSDatabase ++: CoWorkingSpaceSchema

CWSDatabase --> modelCWS --: coworkingspace

controllersCWS <-- modelCWS --:coworkingspace

controllersCWS->client --:response

@enduml

@startuml Manage CoWorkingSpace (PUT)

header Sameple VacQ Sequence Diagram
footer Page %page% of %lastpage%
title "Manage CoWorkingSpace (PUT)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:coworkingspaces" as routerCWS
participant "<<controllers>>\n:coworkingspaces" as controllersCWS
participant "<<model>>\n:CoWorkingSpace" as modelCWS
database "<<MongoDB>>\n:coworkingspaces" as CWSDatabase

client->server ++:req.put('/api/v1/coworkingspaces/:id')

server->routerCWS ++:app.use('/api/v1/coworkingspaces',coworkingspaces)

routerCWS -> controllersCWS ++:updateCoWorkingSpace()

controllersCWS->modelCWS ++:findByIdAndUpdate(id,req.body)

modelCWS ->CWSDatabase ++: CoWorkingSpaceSchema

CWSDatabase --> modelCWS --: coworkingspace

controllersCWS <-- modelCWS --:coworkingspace

controllersCWS->client --:response

@enduml

@startuml Manage CoWorkingSpace (DELETE)

header Sameple VacQ Sequence Diagram
footer Page %page% of %lastpage%
title "Manage CoWorkingSpace (DELETE)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:coworkingspaces" as routerCWS
participant "<<controllers>>\n:coworkingspaces" as controllersCWS
participant "<<model>>\n:CoWorkingSpace" as modelCWS
database "<<MongoDB>>\n:coworkingspaces" as CWSDatabase

client->server ++:req.delete('/api/v1/coworkingspaces/:id')

server->routerCWS ++:app.use('/api/v1/coworkingspaces',coworkingspaces)

routerCWS -> controllersCWS ++:deleteCoWorkingSpace()

controllersCWS->modelCWS ++:findByIdAndDelete(id)

modelCWS ->CWSDatabase ++: CoWorkingSpaceSchema

CWSDatabase --> modelCWS --: coworkingspace

controllersCWS <-- modelCWS --:coworkingspace

controllersCWS->client --:response

@enduml